"""user parameters added

Revision ID: 313e6e32df91
Revises: bdbd41cf8e5e
Create Date: 2021-01-29 22:48:56.190567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '313e6e32df91'
down_revision = 'bdbd41cf8e5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('filter_my', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('filter_public', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('list_page', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'list_page')
    op.drop_column('user', 'filter_public')
    op.drop_column('user', 'filter_my')
    # ### end Alembic commands ###
