"""user add, item->userid foreign

Revision ID: 951862b9d594
Revises: df47ab582f01
Create Date: 2021-01-14 23:33:04.633086

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text


# revision identifiers, used by Alembic.
revision = '951862b9d594'
down_revision = 'df47ab582f01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('image', 'image_temp')
    op.rename_table('item', 'item_temp')

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('item',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('num_of_ad', sa.String(length=32), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('extended_text', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('key')
    )

    op.drop_index('ix_item_description', table_name='item_temp')
    op.drop_index('ix_item_num_of_ad', table_name='item_temp')
    op.create_index(op.f('ix_item_description'), 'item', ['description'], unique=False)
    op.create_index(op.f('ix_item_num_of_ad'), 'item', ['num_of_ad'], unique=True)

    op.create_table('image',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('num_of_ad', sa.String(length=32), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['num_of_ad'], ['item.num_of_ad'], ),
    sa.PrimaryKeyConstraint('key')
    )

    conn = op.get_bind()
    conn.execute(
        text(
            """
            INSERT INTO user (creation_date, username, email) 
            VALUES ("14.01.2021", "_sys_import", "sysimport@localhost")
            """
        )
    )

    conn.execute(
        text(
            """
            INSERT INTO item (description, num_of_ad, creation_date, address, price, extended_text)
            SELECT description, num_of_ad, creation_date, address, price, extended_text
            FROM item_temp
            """
        )
    )

    conn.execute(
        text(
            """
            UPDATE item SET user_id = 1
            """
        )
    )

    conn.execute(
        text(
            """
            INSERT INTO image (num_of_ad, image_path)
            SELECT num_of_ad, image_path
            FROM image_temp
            """
        )
    )

    op.drop_table('image_temp')
    op.drop_table('item_temp')
	
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('image', 'image_temp')
    op.rename_table('item', 'item_temp')
    
    op.create_table('item',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('num_of_ad', sa.String(length=32), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('extended_text', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )

    op.drop_index('ix_item_description', table_name='item_temp')
    op.drop_index('ix_item_num_of_ad', table_name='item_temp')
    op.create_index(op.f('ix_item_description'), 'item', ['description'], unique=False)
    op.create_index(op.f('ix_item_num_of_ad'), 'item', ['num_of_ad'], unique=True)

    op.create_table('image',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('num_of_ad', sa.String(length=32), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['num_of_ad'], ['item.num_of_ad'], ),
    sa.PrimaryKeyConstraint('key')
    )

    conn = op.get_bind()

    conn.execute(
        text(
            """
            INSERT INTO item (description, num_of_ad, creation_date, address, price, extended_text)
            SELECT description, num_of_ad, creation_date, address, price, extended_text
            FROM item_temp
            """
        )
    )

    conn.execute(
        text(
            """
            INSERT INTO image (num_of_ad, image_path)
            SELECT num_of_ad, image_path
            FROM image_temp
            """
        )
    )

    op.drop_table('image_temp')
    op.drop_table('item_temp')

#    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
