"""add user_field in item status

Revision ID: bdbd41cf8e5e
Revises: 20998db684a7
Create Date: 2021-01-28 01:27:57.944998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdbd41cf8e5e'
down_revision = '20998db684a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_status', sa.Column('usr_desc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_status', 'usr_desc')
    # ### end Alembic commands ###
