"""Image table added

Revision ID: df47ab582f01
Revises: 2bf098c4b83c
Create Date: 2021-01-04 14:09:18.875051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df47ab582f01'
down_revision = '2bf098c4b83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('key', sa.Integer(), nullable=False),
    sa.Column('num_of_ad', sa.String(length=32), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['num_of_ad'], ['item.num_of_ad'], ),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
